
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "${PORTFOLIO_PORT}:${PORTFOLIO_PORT}"
    env_file: 
      - .env
    volumes:
      - .:/app
    depends_on:
      - portfolio_data
    networks:
      - project_network
    restart: always

  portfolio_data:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_portfolio:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - project_network
    restart: always


volumes:
  postgres_data_portfolio:

networks:
  project_network:
    external: true 


