default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  sslmode: require  # Habilita o uso de SSL para a conexão

development:
  adapter: sqlite3  # Usando SQLite para desenvolvimento
  database: db/development.sqlite3


test:
  adapter: sqlite3  # Usando SQLite para desenvolvimento
  database: db/development.sqlite3

production:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
