default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["PGHOST"] || ENV["POSTGRES_HOST"] %>
  port: <%= ENV["PGPORT"] || 5432 %>
  username: <%= ENV["PGUSER"] || ENV["POSTGRES_USER"] %>
  password: <%= ENV["PGPASSWORD"] || ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["PGDATABASE"] || ENV["POSTGRES_DB"] %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV["PGDATABASE"] || "development_db" %>

test:
  <<: *default
  database: <%= ENV["PGDATABASE"] || "test_db" %>

production:
  <<: *default
  database: <%= ENV["PGDATABASE"] || ENV["POSTGRES_DB"] %>
  url: <%= ENV["DATABASE_URL"] %>
  sslmode: <%= ENV["SSL_CERT_DAYS"] ? "require" : "disable" %>
