# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: <postgresql>_development

test:
  <<: *default
  database: <postgresql>_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
